version: '3.8'
services:
  redis:
    image: redis:7-alpine

  runner:
    build:
      context: .
      target: runner
    init: true
    restart: always
    volumes:
      - ${PWD}:/app

  #test_mathjs:
  #  build:
  #    context: .
  #    target: test_mathjs
  #  init: true
  #  volumes:
  #    - ${PWD}:/app